export type Language = 'en' | 'zh';

export const platformAgreements = [
  {
    name: 'GitHub Copilot',
    clause: { en: 'Public code used to train Copilot. Business plans may use your code for model improvement.', zh: '公开代码被用于训练 Copilot。商业版可能使用你的代码进行模型改进。' },
    risk: 'high' as const,
    trains: { en: 'Code generation AI → replaces junior developers', zh: '代码生成 AI → 替代初级开发者' },
  },
  {
    name: 'ChatGPT / OpenAI',
    clause: { en: 'Conversations used for model training unless opted out in settings.', zh: '对话内容默认用于模型训练，除非在设置中关闭。' },
    risk: 'high' as const,
    trains: { en: 'General AI capabilities → replaces knowledge workers', zh: '通用 AI 能力 → 替代知识工作者' },
  },
  {
    name: 'Google Workspace',
    clause: { en: 'Data may be used to improve AI-powered features in Workspace products.', zh: '数据可能用于改进 Workspace 产品中的 AI 功能。' },
    risk: 'medium' as const,
    trains: { en: 'Document/email AI → replaces admin & assistants', zh: '文档/邮件 AI → 替代行政与助理' },
  },
  {
    name: 'Microsoft 365 Copilot',
    clause: { en: 'Organizational data feeds AI features. Grounding data used in real-time.', zh: '组织数据为 AI 功能提供支持，实时使用基础数据。' },
    risk: 'medium' as const,
    trains: { en: 'Office productivity AI → replaces analysts', zh: '办公效率 AI → 替代分析师' },
  },
  {
    name: 'LinkedIn',
    clause: { en: 'Profile data, posts, and interactions used for AI-powered recommendations and features.', zh: '个人资料、帖子和互动用于 AI 推荐和功能。' },
    risk: 'high' as const,
    trains: { en: 'Recruiting AI → automates hiring decisions', zh: '招聘 AI → 自动化招聘决策' },
  },
  {
    name: 'Slack',
    clause: { en: 'Messages analyzed for AI search and summary features. Enterprise controls available.', zh: '消息被分析用于 AI 搜索和摘要功能。企业版可控。' },
    risk: 'medium' as const,
    trains: { en: 'Workplace AI → automates communication workflows', zh: '职场 AI → 自动化沟通流程' },
  },
  {
    name: 'Zoom',
    clause: { en: 'Updated 2023: Meeting data may train AI. Opt-out after backlash.', zh: '2023 更新：会议数据可能训练 AI。在反对声中增加了退出选项。' },
    risk: 'low' as const,
    trains: { en: 'Meeting AI → replaces note-takers & schedulers', zh: '会议 AI → 替代记录员和日程安排' },
  },
  {
    name: 'Adobe Creative Cloud',
    clause: { en: 'Creative content analyzed. Firefly trained on Adobe Stock and licensed content.', zh: '创意内容被分析。Firefly 基于 Adobe Stock 和授权内容训练。' },
    risk: 'high' as const,
    trains: { en: 'Image/design AI → replaces junior designers', zh: '图像/设计 AI → 替代初级设计师' },
  },
];

export const dataProtectionTranslations = {
  en: {
    backToHome: '← Back to Home',
    dataThreatTitle: 'Your Data Is Training AI to Replace You',
    dataThreatSubtitle: 'Skill is the last mile from general AI to your specific job. Your experience data is the last defense line.',
    lastMileTitle: 'The Last Mile Problem',
    lastMileDesc: 'A foundation model alone can\'t do your job. But add your industry data, your workflows, your expertise — and it becomes your replacement.',
    lastMileStep1: 'Foundation Model',
    lastMileStep1Desc: 'General capability, no specialization',
    lastMileStep2: 'Your Data & Experience',
    lastMileStep2Desc: 'Industry knowledge, workflows, expertise',
    lastMileStep3: 'Your Replacement',
    lastMileStep3Desc: 'AI that does YOUR specific job',
    lastMileArrow1: 'Fine-tuning / Skills',
    lastMileArrow2: 'Specialization',
    lastMileWarning: 'The more open your experience data is, the faster AI crosses the last mile to replace you.',
    platformTitle: 'What You Already Agreed To',
    platformSubtitle: 'Most people unknowingly "agreed" to let their data train AI. Here\'s what\'s in the fine print:',
    platformName: 'Platform',
    platformClause: 'AI Training Clause',
    platformRisk: 'Risk',
    platformTrains: 'What It Trains',
    platformRiskHigh: 'Explicit Training',
    platformRiskMedium: 'Ambiguous',
    platformRiskLow: 'Opt-out Available',
    feedbackLoopTitle: 'The Feedback Loop',
    feedbackLoopDesc: 'You create data → Company collects it → AI trains on it → AI replaces you → Company profits',
    feedbackLoopExample: 'Real example: Developers wrote code on GitHub → Copilot trained on it → Companies now hire fewer junior devs',
    feedbackLoopStat: 'The people who created the training data are the first to be replaced.',
    protectionTitle: 'Protect Your Last Defense Line',
    protectionSubtitle: 'Actionable steps to guard your experience data:',
    protection1: 'Review AI training opt-out settings on every platform you use',
    protection2: 'Understand your employer\'s data collection and AI training policies',
    protection3: 'Develop non-digitizable skills: judgment, relationships, physical craft',
    protection4: 'Keep proprietary knowledge in non-indexed, private formats',
    protection5: 'Know your rights: GDPR (EU) and data protection laws grant you control',
    viewFullDetails: 'View Full Data Protection Guide',
    viewFullDetailsCta: 'See what platforms collect, the feedback loop, and how to protect yourself.',
  },
  zh: {
    backToHome: '← 返回首页',
    dataThreatTitle: '你的数据正在训练 AI 来取代你',
    dataThreatSubtitle: '技能是通用 AI 到专业任务的最后一公里。你的经验数据，是最后一道防线。',
    lastMileTitle: '最后一公里问题',
    lastMileDesc: '基础模型本身做不了你的工作。但加上你的行业数据、你的工作流、你的专业知识——它就变成了你的替代者。',
    lastMileStep1: '基础模型',
    lastMileStep1Desc: '通用能力，无专业化',
    lastMileStep2: '你的数据与经验',
    lastMileStep2Desc: '行业知识、工作流程、专业技能',
    lastMileStep3: '你的替代者',
    lastMileStep3Desc: '能做你具体工作的 AI',
    lastMileArrow1: '微调 / 技能',
    lastMileArrow2: '专业化',
    lastMileWarning: '你的经验数据越开放，AI 就越快跨过最后一公里来取代你。',
    platformTitle: '你签了什么？',
    platformSubtitle: '大多数人在不知情的情况下已经"同意"了让自己的数据训练 AI。以下是细则里写的：',
    platformName: '平台',
    platformClause: 'AI 训练条款',
    platformRisk: '风险',
    platformTrains: '训练了什么',
    platformRiskHigh: '明确训练',
    platformRiskMedium: '模糊条款',
    platformRiskLow: '可选退出',
    feedbackLoopTitle: '死亡循环',
    feedbackLoopDesc: '你创造数据 → 公司收集 → AI 训练 → AI 取代你 → 公司获利',
    feedbackLoopExample: '真实案例：开发者在 GitHub 上写代码 → Copilot 用它训练 → 公司现在减少招聘初级开发者',
    feedbackLoopStat: '创造训练数据的人，是第一批被替代的人。',
    protectionTitle: '保护你的最后防线',
    protectionSubtitle: '立即可行的经验数据保护措施：',
    protection1: '检查你使用的每个平台的 AI 训练退出设置',
    protection2: '了解你的雇主的数据收集和 AI 训练政策',
    protection3: '发展不可数字化的技能：判断力、人际关系、物理技艺',
    protection4: '将专有知识保存在未被索引的私有格式中',
    protection5: '了解你的权利：GDPR（欧盟）和《个人信息保护法》赋予你数据控制权',
    viewFullDetails: '查看完整数据保护指南',
    viewFullDetailsCta: '了解平台数据收集条款、反馈循环和保护措施。',
  },
};
